import { useEffect, useState } from "react";
import Head from "next/head";
import { useTheme } from "next-themes";

import { theme as lightTheme, darkTheme, styled } from "stitches.config";
import { Box, Button, Select, Stack } from "@/components";

const Heading = styled("h1", {
  color: "$foreground",
});

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme, resolvedTheme } = useTheme();

  useEffect(() => setMounted(true), []);

  if (!mounted) return null;

  return (
    <div>
      <Head>
        <title>Next Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box css={{ mb: "$3x" }}>
        <Heading css={{ ml: "$2x" }}>Colors</Heading>
        <br />
        <Box css={{ display: "inline-block" }}>
          {theme !== undefined && (
            <Select
              css={{ mx: "$3x" }}
              value={theme}
              onChange={(e) => setTheme(e.target.value)}
            >
              <option value="dark">Dark Theme</option>
              <option value="light">Light Theme</option>
              <option value="system">System Theme</option>
            </Select>
          )}
        </Box>

        <Box css={{ m: "0", p: "$3x", background: "$background" }}>
          <Stack direction="column" css={{ stackGap: "$2x" }}>
            <Heading as="h2">The current theme is: {resolvedTheme}</Heading>
            <Stack css={{ stackGap: "$2x" }}>
              <Button>Click Me</Button>
              <Button type="outlined">Click Me</Button>
              <Button type="ghost">Click Me</Button>
              <Button type="link">Click Me</Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="success">Click Me</Button>
              <Button colorway="success" type="outlined">
                Click Me
              </Button>
              <Button colorway="success" type="ghost">
                Click Me
              </Button>
              <Button colorway="success" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="danger">Click Me</Button>
              <Button colorway="danger" type="outlined">
                Click Me
              </Button>
              <Button colorway="danger" type="ghost">
                Click Me
              </Button>
              <Button colorway="danger" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="neutral">Click Me</Button>
              <Button colorway="neutral" type="outlined">
                Click Me
              </Button>
              <Button colorway="neutral" type="ghost">
                Click Me
              </Button>
              <Button colorway="neutral" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x", pb: "$3x" }}>
              <Button disabled>Don't Click Me</Button>
            </Stack>
          </Stack>
        </Box>

        <Box
          css={{ m: "0", p: "$3x", background: "$background" }}
          className={
            resolvedTheme === "light" ? darkTheme : lightTheme.toString()
          }
        >
          <Heading as="h2">I should be reversed</Heading>
          <Stack direction="column" css={{ stackGap: "$2x" }}>
            <Stack css={{ stackGap: "$2x" }}>
              <Button>Click Me</Button>
              <Button type="outlined">Click Me</Button>
              <Button type="ghost">Click Me</Button>
              <Button type="link">Click Me</Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="success">Click Me</Button>
              <Button colorway="success" type="outlined">
                Click Me
              </Button>
              <Button colorway="success" type="ghost">
                Click Me
              </Button>
              <Button colorway="success" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="danger">Click Me</Button>
              <Button colorway="danger" type="outlined">
                Click Me
              </Button>
              <Button colorway="danger" type="ghost">
                Click Me
              </Button>
              <Button colorway="danger" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="neutral">Click Me</Button>
              <Button colorway="neutral" type="outlined">
                Click Me
              </Button>
              <Button colorway="neutral" type="ghost">
                Click Me
              </Button>
              <Button colorway="neutral" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x", pb: "$3x" }}>
              <Button disabled>Don't Click Me</Button>
            </Stack>
          </Stack>
        </Box>
      </Box>
    </div>
  );
}
