import { useEffect, useState } from "react";
import Head from "next/head";
import { useTheme } from "next-themes";

import { darkTheme, styled } from "stitches.config";
import { Button } from "@/components";

const Box = styled("div", {
  margin: "$2",
});

const Flex = styled("div", {
  display: "inline-flex",
  flexWrap: "wrap",
  "& > button": { margin: "$2" },
});

export const ThemeSwitchContainer = styled("a", {
  backgroundColor: "transparent",
  padding: "$0",
  "&:hover": {
    cursor: "pointer",
    textDecoration: "underline",
  },
});

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme } = useTheme();

  useEffect(() => setMounted(true), []);

  const toggleTheme = () => {
    if (theme === "dark") {
      setTheme("light");
    } else {
      setTheme("dark");
    }
  };

  if (!mounted) return null;

  return (
    <div>
      <Head>
        <title>Next Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <h1>Colors</h1>
        <br />
        <ThemeSwitchContainer
          type="button"
          data-testid="themeSwitch"
          onClick={toggleTheme}
        >
          {theme === "light" ? "Switch To Dark Mode" : "Switch To Light Mode"}
        </ThemeSwitchContainer>
      </Box>
      <br />
      <br />
      <Flex>
        <Button>Click Me</Button>
        <Button type="outlined">Click Me</Button>
        <Button type="ghost">Click Me</Button>
        <Button type="link">Click Me</Button>
      </Flex>
      <br />
      <Flex>
        <Button colorway="success">Click Me</Button>
        <Button colorway="success" type="outlined">
          Click Me
        </Button>
        <Button colorway="success" type="ghost">
          Click Me
        </Button>
        <Button colorway="success" type="link">
          Click Me
        </Button>
      </Flex>
      <br />
      <Flex>
        <Button colorway="danger">Click Me</Button>
        <Button colorway="danger" type="outlined">
          Click Me
        </Button>
        <Button colorway="danger" type="ghost">
          Click Me
        </Button>
        <Button colorway="danger" type="link">
          Click Me
        </Button>
      </Flex>
      <br />
      <Flex>
        <Button colorway="neutral">Click Me</Button>
        <Button colorway="neutral" type="outlined">
          Click Me
        </Button>
        <Button colorway="neutral" type="ghost">
          Click Me
        </Button>
        <Button colorway="neutral" type="link">
          Click Me
        </Button>
      </Flex>
      <br />
      <Flex>
        <Button disabled>Don't Click Me</Button>
      </Flex>
      <br />
      <br />
      <Box
        css={{ m: "0", py: "$3", background: "$background" }}
        className={darkTheme}
      >
        <Flex>
          <Button>Click Me</Button>
          <Button type="outlined">Click Me</Button>
          <Button type="ghost">Click Me</Button>
          <Button type="link">Click Me</Button>
        </Flex>
        <br />
        <Flex>
          <Button colorway="success">Click Me</Button>
          <Button colorway="success" type="outlined">
            Click Me
          </Button>
          <Button colorway="success" type="ghost">
            Click Me
          </Button>
          <Button colorway="success" type="link">
            Click Me
          </Button>
        </Flex>
        <br />
        <Flex>
          <Button colorway="danger">Click Me</Button>
          <Button colorway="danger" type="outlined">
            Click Me
          </Button>
          <Button colorway="danger" type="ghost">
            Click Me
          </Button>
          <Button colorway="danger" type="link">
            Click Me
          </Button>
        </Flex>
        <br />
        <Flex>
          <Button colorway="neutral">Click Me</Button>
          <Button colorway="neutral" type="outlined">
            Click Me
          </Button>
          <Button colorway="neutral" type="ghost">
            Click Me
          </Button>
          <Button colorway="neutral" type="link">
            Click Me
          </Button>
        </Flex>
        <br />
        <Flex>
          <Button disabled>Don't Click Me</Button>
        </Flex>
      </Box>
    </div>
  );
}
