import { useEffect, useState } from "react";
import Head from "next/head";
import { useTheme } from "next-themes";

import { theme as lightTheme, darkTheme, styled } from "stitches.config";
import { Button } from "@/components";
import { Stack } from "@/components/stack";

const Box = styled("div", {
  margin: "$2x",
});

const Select = styled("select", {
  margin: "$2x",
});

const Heading = styled("h1", {
  color: "$foreground",
  pl: "$2x",
});

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme } = useTheme();
  console.log(theme);
  useEffect(() => setMounted(true), []);

  if (!mounted) return null;
  console.log(theme);
  return (
    <div>
      <Head>
        <title>Next Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading>Colors</Heading>
        <br />
        {theme !== undefined && (
          <Select value={theme} onChange={(e) => setTheme(e.target.value)}>
            <option value="dark">Dark</option>
            <option value="light">Light</option>
            <option value="system">System</option>
          </Select>
        )}
        <br />
        <br />
        <Box css={{ m: "0", p: "$3x", background: "$background" }}>
          <Stack direction="column" css={{ stackGap: "$2x" }}>
            <Stack css={{ stackGap: "$2x" }}>
              <Button>Click Me</Button>
              <Button type="outlined">Click Me</Button>
              <Button type="ghost">Click Me</Button>
              <Button type="link">Click Me</Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="success">Click Me</Button>
              <Button colorway="success" type="outlined">
                Click Me
              </Button>
              <Button colorway="success" type="ghost">
                Click Me
              </Button>
              <Button colorway="success" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="danger">Click Me</Button>
              <Button colorway="danger" type="outlined">
                Click Me
              </Button>
              <Button colorway="danger" type="ghost">
                Click Me
              </Button>
              <Button colorway="danger" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="neutral">Click Me</Button>
              <Button colorway="neutral" type="outlined">
                Click Me
              </Button>
              <Button colorway="neutral" type="ghost">
                Click Me
              </Button>
              <Button colorway="neutral" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button disabled>Don't Click Me</Button>
            </Stack>
          </Stack>
        </Box>
        <br />
        <Box
          css={{ m: "0", p: "$3x", background: "$background" }}
          className={theme === "light" ? darkTheme : lightTheme.toString()}
        >
          <Heading as="h2">I'm should be visible</Heading>
          <Stack direction="column" css={{ stackGap: "$2x" }}>
            <Stack css={{ stackGap: "$2x" }}>
              <Button>Click Me</Button>
              <Button type="outlined">Click Me</Button>
              <Button type="ghost">Click Me</Button>
              <Button type="link">Click Me</Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="success">Click Me</Button>
              <Button colorway="success" type="outlined">
                Click Me
              </Button>
              <Button colorway="success" type="ghost">
                Click Me
              </Button>
              <Button colorway="success" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="danger">Click Me</Button>
              <Button colorway="danger" type="outlined">
                Click Me
              </Button>
              <Button colorway="danger" type="ghost">
                Click Me
              </Button>
              <Button colorway="danger" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button colorway="neutral">Click Me</Button>
              <Button colorway="neutral" type="outlined">
                Click Me
              </Button>
              <Button colorway="neutral" type="ghost">
                Click Me
              </Button>
              <Button colorway="neutral" type="link">
                Click Me
              </Button>
            </Stack>
            <Stack css={{ stackGap: "$2x" }}>
              <Button disabled>Don't Click Me</Button>
            </Stack>
          </Stack>
        </Box>
      </Box>
    </div>
  );
}
